### ISSUE TITLE
v2.0.0 crashes on startup with B[s] is not a function

### ISSUE THREAD

**Issue by owai-dev** [musistudio/claude-code-router#1417]
> Bug: v2.0.0 crashes on startup with B[s] is not a function
  > 
  > Description:
  > After updating to 2.0.0, the router crashes instantly when running ccr start or ccr status. 
  > 
  > Error Details:
  > 
   1 > Failed to parse config file at ~/.claude-code-router/config.json
   2 > Error details: B[s] is not a function (or lp[yn] is not a function)
   3 > ```
   4 > This appears to be a minification bug in the production build (`dist/cli.js`). It crashes during the
     `TransformerService` / `ConfigService` initialization when attempting to parse the `transformers` array from
     the JSON config. Downgrading to `1.0.73` immediately resolves the issue.
   5
   6 ***
   7
   8 ### How to ensure CCR is always running on boot
   9
